on:
  push:
    branches:
      - main

jobs:
  use_ssh_agent:
    runs-on: ubuntu-latest
    name: Start an SSH Agent
    steps:
      - uses: actions/checkout@v4
      - uses: ./
      - run: echo $SSH_AUTH_SOCK;
      - run: echo $SSH_AGENT_PID;
